### PR TITLE
change XML import to handle cgInstances

### PR DESCRIPTION
**Pull request by eyck**
The PR changes the import of XML into the MemDB. If there is only 1 cgInstance in a covergroupCoverage the behavior is the same. If there a several cgInstances they all are imported as list of instances. The report_builder has been updated to correctly handle this and also sum the coverage numbers of the instances. The rounding has been moved to the formatter as premature rounding might lead to issues when summing up large databases.
Attached is a simple xml version illustrating this, using pyucis-viewer it looks like
image
(Separately I will provide a fix for the rounding in viewer)
[test_coverage.xml.zip](https://github.com/fvutils/pyucis/files/8946660/test_coverage.xml.zip)

### CODE REVIEW

**Comment by mballance** [comment]
Hi @eyck, many thanks for the quick work on this one. In reading through the UCIS spec and looking at the FC4SC XML output last night, I realized that I overlooked the fact that covergroupCoverage can be inside instanceCoverage (here, again, the lack of XML examples makes things tricky). I now believe the file structure should look like:
- covergroupCoverage
    - cgInstance (represent type coverage for TYPE1)
    - cgInstance (represent type coverage for TYPE2)
- instanceCoverages
    - covergroupCoverage
        - cgInstance (represent instance coverage for TYPE1)
        - cgInstance (represent instance coverage for TYPE1)
        - cgInstance (represent instance coverage for TYPE2)

This PR is definitely heading in the right direction. 
- I'd like to have the type coverage processed if it is present. If it isn't, then your approach of merging the instance coverage is fine
- We need to ensure the writer does the correct thing as well.

I'm going to merge this onto a branch until we can merge the complete changes back.

**Comment by mballance** [comment]
Okay, I've created a new branch (xml-format-fc4sc) and merged your changes there. I'll look at updating the XML writer. Will you add in processing of type coverage from the covergroupCoverage/cgInstance entries?

**Comment by eyck** [comment]
If you look at https://github.com/Minres/pyucis/blob/c73384eb15e3d6de58459c1f24d4d4d3306639ad/src/ucis/report/coverage_report_builder.py#L77 it is already there

**Comment by eyck** [comment]
> Hi @eyck, many thanks for the quick work on this one. I'm still a little unsure about treating instances as having two different meanings if there is 1 (it's type coverage) vs >1 of them (it's instance coverage). This may be the correct interpretation, but I see some other elements in the XML, such as instanceId/parentInstanceId that might also be used to establish type/instance relationships. Let's proceed with the interpretation that you're using for now. I will see if I can confirm how a commercial tool interprets the data.

Those ids reflect the design hierarchy. From the spec (9.6 INSTANCE_COVERAGE schema):: 

> Identifier of the parent instance in the design hierarchy.

So they are not intended for coverage type/instance relationships.

**Pull request merged**
